version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: 4320_final_project
    container_name: 4320_final_project_container
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1